/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ShoppingApp.view.DeliveryForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.DeliveryForm',
    xtype: 'deliveryform',
 
    config: {
        itemId: 'DeliveryForm',
        items: [
            {
                xtype: 'fieldset',
                title: 'Registration Form',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Username',
                        labelWrap: true,
                        name: 'username',
                        placeHolder: 'Enter Username'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Password',
                        labelWrap: true,
                        name: 'password',
                        placeHolder: 'Enter Password'
                    },
                    {
                        xtype: 'emailfield',
                        label: 'Email',
                        labelWrap: true,
                        name: 'email',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'urlfield',
                        label: 'Website',
                        labelWrap: true,
                        name: 'website',
                        placeHolder: 'http://example.com'
                    },
                    {
                        xtype: 'textareafield',
                        label: 'About You',
                        labelWrap: true,
                        name: 'aboutyou',
                        placeHolder: 'Tel me about yourself'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'save',
                width: '30%',
                text: 'Save'
            }
        ],
		listeners: [
            {
                fn: 'onFormSave',
                event: 'tap',
                delegate: '#save'
            }
        ]
    },
	onFormSave: function(button,e,options){
 
		var formObj = button.up('FormPanel');
		var formData = formObj.getValues();
		 
		var usr = Ext.create('MyApp.model.User',{
			 username: formData.username,
			 password: formData.password,
			 email:formData.email,
			 website:formData.website,
			 aboutyou: formData.aboutyou
		});
		 
		var errs = usr.validate();
		var msg = '';
		 
		if (!errs.isValid()) {
		   errs.each(function (err) {
		   msg += err.getField() + ' : ' + err.getMessage() + '<br/>';
		   });
		 
		   Ext.Msg.alert('ERROR', msg);
		 
		} else {
			 var userStore = Ext.getStore('userstore');
			 userStore.add(usr);
			 userStore.sync();
			  Ext.Msg.alert('SUCCESS', 'Data Saved to Local Storage Successfully');
		}
 
	}
});